### ISSUE TITLE
Will this project work in browser?

### ISSUE THREAD

**Issue by QQCif** [privateOmega/html-to-docx#3] opened 2020-06-28 12:54 UTC
Searched NPM and found this project. Tried in browser but gives me error about fs. Is this project for node only or I miss some settings...

**Comment by privateOmega** [comment] 2020-06-29 05:03
@QQCif Currently this project was made targeting both Node and Frontend frameworks like React, Vue etc. But I will try to add direct browser support ASAP.

**Comment by privateOmega** [comment] 2020-07-21 11:20
Working on this under [feature/browser-example](https://github.com/privateOmega/html-to-docx/tree/feature/browser-example)

**Comment by BikashKNayak** [comment] 2020-08-11 19:24
I installed this in my react typescript application but gives node js related errors such as 
Error: Can't resolve 'child_process' in \node_modules\libtidy-updated\node_modules\detect-libc\lib'

**Comment by anirudh-modi** [comment] 2020-09-14 10:35
@privateOmega what will be the state of the branch for the browser support?

**Comment by josx** [comment] 2020-09-16 17:32
The problem is that https://github.com/gagern/node-libtidy is not for browser.

**Comment by privateOmega** [comment] 2020-09-16 18:04
@BikashKNayak @anirudh-modi Sorry for the late reply, I haven't been following this project as much as I would like to due to other commitments. The problem with implementing this package in browser is exactly like @josx said, I started working on this project with an aim to support both ends of the stack but I had to import node-libtidy into the package which essentially cleans up HTML and only works in node environment. Since I have multiple people interested in this being implemented at browser, I will try to work on the package ASAP, removing node-libtidy dependency and supporting browsers. Anyone who is interested can also take this up.

**Comment by privateOmega** [comment] 2020-10-06 05:49
Removed the libtidy dependency.

**Comment by josx** [comment] 2020-10-07 12:05
great!

**Comment by itsmhuang** [comment] 2020-10-08 21:16
Is there any update on how this can work with browser now?

**Comment by tenthousandfiRe** [comment] 2020-10-19 11:48
I'm interested on how this can work with browser

**Comment by evrardts** [comment] 2020-10-19 15:23
Same here, would love to see it working in the browser. Thanks a lot!

**Comment by redbrain** [comment] 2020-10-26 16:26
+1 for browser support. I'll comment so I'm notified of progress.

**Comment by redbrain** [comment] 2020-10-26 19:00
You can look into alternative libraries like [tidy-html5](https://www.npmjs.com/package/tidy-html5) which is just libtidy compiled to browser JS using emscripten. However, it's less performant and only supports synchronous operation.

**Comment by privateOmega** [comment] 2020-10-28 21:05
Guys, I am delighted to know that people have noticed my very first OSS package, thanks for the following.
But I am extremely sorry that I haven't been able to spend some time to follow up on the issues created in this repo, being quite busy with my work.
All that apart I was able to spend some time to figure out the issue at hand finally and I have good news and bad news.

Good news - Figured out the problematic dependency and removed it in feature/browser-example branch, a minifier plugin called `html-minifier` was the culprit. And I tested this out in react environment and it seems to work well, except for some white-spacing issue.
Replacement is plain regex as of now. :/

Bad news - In browser, I am getting an error of an import from `html-to-vdom` is giving me undefined instead of the function it should be returning, but from some googling I am certain that it is due to a circular dependency, which I will try to resolve ASAP and this should be good to ship for browser usage as well.

Cheers

**Comment by ronanjia** [comment] 2021-03-10 03:00
hi, @privateOmega, Help please, sorry i just can't get it to work in browser.
i installed the feature/browser-example branch, and only got '/example' and '/node_modules' 2 directories in my 'html-to-docx' package
![image](https://user-images.githubusercontent.com/5581839/110495615-a49b0180-812f-11eb-8c4c-0b36f5f0e0d0.png)

I thought some key files might be lost, so i copied '/src', '/template', 'index.js' into the package folder, just got the same error of  Can't resolve 'crypto', 'fs', 'path' when i run from "generateContainer" in index.js
![image](https://user-images.githubusercontent.com/5581839/110496015-0a878900-8130-11eb-87f2-282e94949fb6.png)

So is it possible to use this package in a react or an angular project for browser?

**Comment by redbrain** [comment] 2021-03-10 12:54
hi @ronanjia !
Currently, this project isn't functional in browser, that's why this issue is open. It'll be closed when browser support is released.
Until then, try using another, such as https://github.com/evidenceprime/html-docx-js . Not as good, but browser supported.

**Comment by privateOmega** [comment] 2021-05-01 12:46
Guys, I am extremely sorry about turning a blind eye towards this much requested feature for so long, I was so occupied with other things, that I wasn't able to put in any time on this and get this feature out, but today I did spend some time and it seems like there's some issue that I am facing with `npm` specifically and not `yarn` and seems like that was the culprit all along and it was misleading me as well when I last worked on this. I will raise a PR now itself after rebasing the branch and hopefully this should be out with next version release.

**Comment by privateOmega** [comment] 2021-05-01 12:47
@ronanjia Thanks a lot for posting this, it helped me find that this happens only when you try installing with npm and not yarn. Could you please try with yarn and post the result here?

**Comment by privateOmega** [comment] 2021-06-05 12:22
Finally released a new version which contains the changes for browser support, even though it doesn't have support for direct usage using script tag, but it does work with React, so yay. :D

Closing this issue.

**Closed by privateOmega** 2021-06-05 12:22 UTC

**Comment by wnabil** [comment] 2021-07-25 16:02
@privateOmega i got `Cannot call a class as a function` using the latest version 1.2.2 when tsconfig is targeting es5
`import * as HTMLtoDOCX from 'html-to-docx'; or import HTMLtoDOCX from 'html-to-docx'; const HTMLtoDOCX = require('html-to-docx');` did not help

the project have to target ES2015 then it will work.

**Comment by artemdumanov** [comment] 2023-06-21 13:39
As a workaround, you can use 
`// @ts-ignore`

**Comment by haykeminyan** [comment] 2023-10-19 10:15
could you check please this error with doc/docx?
**ERROR Export type is not supported.**
I can't export data into docx... changed es2020 to es2015 and seems no changes. All other types are working except doc/docx(
