### ISSUE TITLE
Html-to-docx not working after creating a build of project and severing it

### ISSUE THREAD

**Issue by parthdhoriya** [privateOmega/html-to-docx#142] opened 2022-08-18 12:02 UTC
I have a project in my local everything works fine in local but as soon as i create a build of my project and try to serve to project and then try to convert a sample html string to word then its showing below error
![image](https://user-images.githubusercontent.com/93188565/185389879-ea4a9c4d-aeef-40ca-9f04-dd6b2791263b.png)

**Comment by MateuszGrzymowicz** [comment] 2022-08-29 12:39
Same problem here

**Comment by diogoalmiro** [comment] 2022-11-09 10:56
Having the same problem

**Comment by privateOmega** [comment] 2022-11-10 17:25
@parthdhoriya @MateuszGrzymowicz @diogoalmiro Could you please post the deps list, some configuration, logs and possibly a sandbox as well for me to replicate this issue?

**Comment by privateOmega** [comment] 2022-11-17 19:12
@parthdhoriya @MateuszGrzymowicz @diogoalmiro This is a duplicate of https://github.com/privateOmega/html-to-docx/issues/92 and I've just released v.1.6.3 which should address it. Please test and if issue persists, feel free to reopen this.

**Closed by privateOmega** 2022-11-17 19:12 UTC
