### ISSUE TITLE
Elements following headers get header style in Mac Pages

### ISSUE THREAD

**Issue by tasola** [privateOmega/html-to-docx#180] opened 2023-01-11 15:22 UTC
Hi!

When I have a header (e.g. h1) with some following element(s) (e.g. p), the latter elements get interpreted as headers as well. For instance, if I pass the following html string:

```
<!DOCTYPE html>
<head>
   <meta charset='UTF-8'>
   <title>The useEffect hook (updated)</title>
</head>
<body>
   <div>
      <h1>Heading</h1>
      <p>This gets big and bold as well</p>
   </div>
</body>
</html>
```

the downloaded document looks like this:

![Screenshot 2023-01-11 at 16 21 37](https://user-images.githubusercontent.com/24315038/211844747-c3cc5d00-734b-476f-992c-e3bd3cec12ab.png)

The same goes for any kinds and amount of subsequent elements. If I would put the paragraph before the h1 in the example above, the paragraph would be rendered correctly as a p.

I tried to look around for any similar issue, but I couldn't find any. Can you tell if I'm doing something wrong, or is this a bug?

**Comment by nicolasiscoding** [comment] 2023-01-13 13:02
I personally don’t see this issue, but can say the best way to triage it is
to fix it by hand and do a diff of the OOXML tags to see how pages renders
it.

From there, you can make a PR with an option such as “forMacPages: true”
or something like that. Maybe there’s a way it can support both?

**Comment by tasola** [comment] 2023-01-13 13:52
@nicolasiscoding Cool, thanks for the input. I'll look into it if I get some time.

Just to be clear - you're not experiencing the same thing if you run the function with the html in my initial post, with version `1.6.4` of html-to-docx and open it in Mac Pages...?

**Comment by privateOmega** [comment] 2023-01-17 18:47
@tasola So I tested the corresponding output on multiple word processors, seems like the issue is on mac pages only. Attaching the screenshot for reference. 

**word**
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/10467133/212984849-66a8deeb-d615-45c9-86a6-62bfe31508f7.png">

**libre office**
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/10467133/212984906-375d2ef4-3b1d-4ab4-b2bb-1912760d1c0d.png">

**mac pages** 
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/10467133/212984936-a668a85f-25a2-473c-832f-7fc698896f23.png">


@nicolasiscoding I think to debug this problem, its gonna be super hard considering each word processor might work differently based on order of tags etc. And I wouldnt suggest changes being proposed based on each word processor since that would complicate things further. 

Closing this issue since issue isnt with html-to-docx, but with the viewer application. Please feel free to reopen it if you think I made a mistake.

**Closed by privateOmega** 2023-01-17 18:47 UTC
