### ISSUE TITLE
Html raw content to docx - unable to render base64 image to docx and formatting content issue

### ISSUE THREAD

**Issue by jyotisonghare** [privateOmega/html-to-docx#48] opened 2021-01-22 10:31 UTC
@privateOmega , previously we used html-docx-js to generate docx.
 In which we provide htmlContent in payload and pass it to package. Please go through the attachment where you will get 3 files html-docx-js output , html-to-docx output file and html content input file. Please let us know what we are doing wrong we are expecting the same result from html-to-docx package also.
 Any help would be appreciated.

 Thank you ! 

[html-docx-js output.zip](https://github.com/privateOmega/html-to-docx/files/5855527/html-docx-js.output.zip)

**Comment by privateOmega** [comment] 2021-01-22 15:01
@jyotisonghare Sorry to burst your bubble, but this project isn't recommended for use in production ready code and might have to work out a lot of kinks. Since I am the only primary developer on this and I can't commit to this as much as I would like to due to my other commitments, I would suggest you to open individual issues, so hopefully I can take it up as much as I can, rather than you giving me a super big html to debug. Btw, I had checked the html it seems like base64 image is rendered, check the first page, I guess the problem is when content comes inside table cell and as part of list element. 

Considering your html seems advanced, I would suggest using html-docx-js, that project use a feature called alt-chunks which converts embeds html in docx, making it look as you want it to be.

Sorry to be brutal, but this is the reality. Thanks for using the library.

**Comment by mahendra119** [comment] 2021-01-22 17:15
Hi @privateOmega , Thanks for the response
html-docx-js doesn't provide support for skipping header/footer on the first page which is our top priority right now. 

Could you suggest in html-docx-js which files are used for making header/footer so that we can check?

**Comment by privateOmega** [comment] 2021-01-25 11:15
@mahendra119 Tbh html-docx-js is a different project altogether and if at present it doesn't have it, someone has to make a contribution to it for the same, not something I can help you with.

@jyotisonghare I am closing this issue due to it being non-specific to solve at present. Feel free to reopen it if you could be specific with your issues.

**Closed by privateOmega** 2021-01-25 11:15 UTC

**Comment by amrita-syn** [comment] 2021-02-09 07:27
> Hi @privateOmega , Thanks for the response
> html-docx-js doesn't provide support for skipping header/footer on the first page which is our top priority right now.
> 
> Could you suggest in html-docx-js which files are used for making header/footer so that we can check?

We are now supporting skipping header on first page.
