### ISSUE TITLE
Skip header/footer or different header/footer on first page

### ISSUE THREAD

**Issue by mahendra119** [privateOmega/html-to-docx#46] opened 2021-01-14 12:26 UTC
Hello,
First of all, it is a great package but I ran into one issue when I am setting headerType to "First or even", it is not working at all. It only works when set to "default" option. Also is there any setting where we can skip header/footer on the first page or show different header/footer on first page.
I have installed this package and it contains file in minified version so I am not able to find the code that you have added in PR.

Any help would be appreciated. Thanks

**Comment by privateOmega** [comment] 2021-01-14 17:28
Closing this issue, since it's a duplicate of #44 . Please follow the issue of the progress in #45 .

**Closed by privateOmega** 2021-01-14 17:28 UTC

**Comment by mahendra119** [comment] 2021-01-20 12:54
Thank you very much @privateOmega. You have saved us a lot of time.
